version: '3.4'

#create a volume for the my sql container.To ensure Data persists after my sql container is stopped
volumes:
  datafiles:
  static:

services:
  #DataBase Service
  database:
    #Pull the latest mysql image
    image: mysql:8.0.27
    #Specify where the persisted Data should be stored
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    #Specify Environment Variables for mysql
    environment: 
      MYSQL_ROOT_PASSWORD: R00t
      MYSQL_DATABASE: Bowling
    networks:
      - bowlingApi-net
  #Api  Service
  api:
    image: bowlinggame_api
    build:
      context: .
      #Use the DockerFile in that Directory
      dockerfile: Dockerfile
    #This Service Depends on the database service specifed above
    depends_on: 
      - database
    networks:
      - bowlingApi-net
    volumes:
     - static:/var/lib/api
    ports:
        - 8080:5000
networks:
  bowlingApi-net:  
    driver: bridge